// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxdewrmbuyvskepmfxwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZGV3cm1idXl2c2tlcG1meHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTczMTIsImV4cCI6MjA3NDA5MzMxMn0.hPcMcE67G6f7mvAUptnA7lpblStlzi1uRrnSAHLbLKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});